function out1 = fdDdN(Gamma)
%FDDDN
%    OUT1 = FDDDN(GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    15-Feb-2017 09:31:49

t2 = Gamma-5.551159304161843e4;
out1 = (t2.^2.*(-3.245133880675725e-9)+9.999999999999998).^(9.0./2.0).*(2.99e2./1.0e2);
