function [dsigma] = fDsigma(x, lambda, T, tau0)
%FDSIGMA
%    OUT1 = FDSIGMA(X)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    15-Feb-2017 09:31:49

dsigma = 2/(lambda*T)*tau0*sin(lambda*x);
